### ISSUE TITLE
CLIP解码器维度不匹配问题

### ISSUE THREAD

**Issue by ghost** [hutuo1213/48.02#3]
![1](https://github.com/user-attachments/assets/d21d9566-e215-42b7-980d-8342181abded)
![2](https://github.com/user-attachments/assets/dca3d772-240e-43b8-944b-9900fa20c404)
作者，您好，打扰您一下，我在复现您的代码过程中，出现了一个问题，在PViC的forward函数中调用clip_decoder出现了维度不匹配的问题，经过我的排查，我怀疑问题出在ClipTransformerDecoderLayer类中，所以再次找到您，请问一下，可不可以分享一下上述图片中两个类的代码，我学习一下您的思路，感谢！

**Comment by hutuo1213** [comment]
您好，我想先确定您是如何获得CLIP的图像特征的？我们是参考了HOICLIP中的contextual的全局特征。
它位于clip的model.py中。

```python
    def forward(self, x: torch.Tensor):
        x = self.conv1(x)  # shape = [*, width, grid, grid]
        x = x.reshape(x.shape[0], x.shape[1], -1)  # shape = [*, width, grid ** 2]
        x = x.permute(0, 2, 1)  # shape = [*, grid ** 2, width]
        x = torch.cat([self.class_embedding.to(x.dtype) + torch.zeros(x.shape[0], 1, x.shape[-1], dtype=x.dtype, device=x.device), x], dim=1)  # shape = [*, grid ** 2 + 1, width]
        x = x + self.positional_embedding.to(x.dtype)
        x = self.ln_pre(x)

        x = x.permute(1, 0, 2)  # NLD -> LND
        x = self.transformer(x)
        x = x.permute(1, 0, 2)  # LND -> NLD

        # contextual = self.ln_post(x[:, :, :])
        contextual = self.ln_post(x)

        x = self.ln_post(x[:, 0, :])

        if self.proj is not None:
            x = x @ self.proj
            # contextual = contextual @ self.proj

        return x, contextual
```
另外，debug应该可以解决一切维度问题。我会在稍晚一些上传该部分代码。

**Comment by caochong12** [comment]
感谢！按照您说的利用CLIP获取特征的方法，我已经解决了我所犯的错误，因为我用了ViPLO中CILP的方法导致维度不匹配，感谢您提出的建议！
但是我现在在训练的过程中遇到了一个棘手的问题，问题如下所示：
`Traceback (most recent call last):
  File "/home/xml/anaconda3/envs/upt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/media/xml/F/caochong/pvic-CLIP/main.py", line 128, in main
    engine(args.epochs)
  File "/media/xml/F/caochong/pvic-CLIP/pocket/pocket/core/distributed.py", line 139, in __call__
    self._on_each_iteration()
  File "/media/xml/F/caochong/pvic-CLIP/utils.py", line 219, in _on_each_iteration
    self._state.loss.backward()
  File "/home/xml/anaconda3/envs/upt/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/xml/anaconda3/envs/upt/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function MmBackward returned an invalid gradient at index 1 - got [1024, 384] but expected shape compatible with [256, 384]`

出现问题的代码在utils.py中的CustomisedDLE类中，具体位置截图如下：
![3](https://github.com/user-attachments/assets/16605d1f-a7f0-4c8c-baee-6f907e2d7cad)


我利用了debug去查看问题，但是并没有发现有相应的矩阵，是不是我在pvic的forward函数中数据处理出现的问题？请问您出现过类似的情况吗？

**Comment by hutuo1213** [comment]
这部分是梯度下降优化，应该是向量的维度出现了问题，您因该仔细检查网络结构的维度。PViC由于引入了`条件DETR`，所以代码会复杂一点。您可以使用chatGPT等AI软件快速阅读该部分代码，并debug查看维度。

**Comment by caochong12** [comment]
好的，我会继续尝试改动这部分代码！感谢！
